version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/app

    steps:
      - run:
          name: Checkout code
          command: |
            # Preapprovve github by adding their public key to known_hosts. Allows interactionless git checkouts.
            # The following key is fetched from `ssh-keyscan github.com`
            mkdir ~/.ssh
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts

            git clone $CIRCLE_REPOSITORY_URL -b $CIRCLE_BRANCH ~/app --depth=1

      - run:
          name: install node deps
          command: |
            npm install

      - run: npm test
