version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/app

    steps:
      - run:
          name: Checkout code
          command: |
            git clone $CIRCLE_REPOSITORY_URL -b $CIRCLE_BRANCH ~/app --depth=1

      - run:
          name: install node deps
          command: |
            npm install

      - run: npm test
