version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install node deps
          command: |
            sed "s/YOUR_TOKEN_HERE/$FA_KEY/" ./examples/npmrc/npmrc > ./.npmrc
            npm install

      - run: npm run test-ci
